# Usar una imagen base de node
FROM node:latest

# Crear y establecer el directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
#COPY package*.json ./

# Instalar dependencias
#RUN npm install

# Copiar el resto de la aplicación
#COPY . .

# Exponer el puerto
#EXPOSE 3000

# Comando por defecto
CMD ["npm", "start"]
